#- hosts: dsp
#  tasks:
#    - name: Include mute mains
#      include_tasks: mute_mains.yml

- name: Include OS-specific system setup tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "prepare_{{ ansible_os_family | lower }}.yml"
      skip: true

- name: Include Reaper host tasks
  include_tasks: prepare_reaper.yml
  when: "'reaper' in group_names"


#- hosts: ableton
#  tasks:
#    - name: Include Ableton setup tasks
#      include_tasks: prepare_ableton.yml

#- hosts: dsp
#  tasks:
#    - name: Include unmute mains
#      include_tasks: unmute_mains.yml